### ISSUE TITLE
Other way to solve Flag Geo 4

### ISSUE THREAD

**Issue by HappyLer** [JaneBdemented/NSEC2020_The_Truth_About_Mr_Smiley#1]
There was an other way to solve Geo 4. The background image on the "You are not Ben Smiley !"  page is "/img/image97.png". Changing this to "/img/image98.png" also gives you the flag. Can you add this into your write-up, since I do not plan on writing one for this little difference? 
Also, the first flag could be found using strings (I also did it with volatility).

**Comment by JaneBdemented** [comment]
Thanks, added the info about the image. The Geo 1 Flag already admits to the ability to pull the flag by using strings.
